# Generated by Django 4.0.2 on 2022-02-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Planet',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='verified_place',
        ),
        migrations.AddField(
            model_name='planet',
            name='verified_planet',
            field=models.BooleanField(default=False),
        ),
    ]
