# Generated by Django 4.0.2 on 2022-02-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='user',
        ),
    ]
