# Generated by Django 4.0.2 on 2022-02-14 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_planet_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
