# Generated by Django 4.0.2 on 2022-02-16 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0007_planet_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-16 11:30:59'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.CharField(default='profile', max_length=200)
        ),
        
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.planet'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='ana', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planet',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
