# Generated by Django 4.0.2 on 2022-02-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_profile_bio_user_avatar_user_bio_alter_profile_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='bio', max_length=300),
        ),
    ]
