# Generated by Django 4.0.2 on 2022-02-16 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_profile_address'),
        ('main_app', '0011_remove_comment_name'),
    ]

    operations = [
    ]
