# Generated by Django 4.0.2 on 2022-02-17 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_comment_planet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='planet',
            field=models.OneToOneField(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.planet'),
        ),
    ]
