# Generated by Django 4.0.2 on 2022-02-17 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_comment_planet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='planet',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='planet_comments', to='main_app.planet'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='main_app.user'),
        ),
    ]
